travis:
  secure:
    BINSTAR_TOKEN: HPu3itE//qH1BS6otWnHNKBjYPOk2cYL4ezWYSp8vUSc5zmUToZ4WeSLnrhBHu9183gSR1yqsv+f3iZ7nVV2tvFW6iFPHiSUvHAtjHDJxN5AWCPCtOCzbL8YqsF5fwOoJ6K3e1K2QafnnY5KydIbQ3aIH3rEV41N1hJ+qZ38QtXTS/NrcFtInOMcxhcQ5M9Ir8bdVLWKJm4vZmcZ1qefNk9EbEyGkMeiIgcmA9W380LVStJ6g4vv5YtwgzCjYufDqhXslkQXqE2bQ7iGlF0h/B3keAeeTTfULUYktw87SG+pXWdWrQjuT5XtTsSpNqj+s3X/fIIAaGBT/qKOxv/G2nZNnAmu5VoOJ1NsArwzoCv9KVMRSMqulsOj7BCteEPgmggysNik/PSOuJtujwBQ2Y3c4tD99iy91Ln8BfaVzru8cjopSF4bijTkqeGa8rzdk3PGsgqixT2Jo1yDJ+rI0EZghtMxcaGM1X3+ZqjBUUGu7dHtlOSrE4jVI/1ZhqnY/o7f7jS6GY2VTNua2+XuIcWwei2uXuuwnUY1rFyg/lxW04aZTqJVxTMU3pMnSAb12mvrahdln5f7+7EdSKYSrG/pGKzCAJ8jkGIlStvWN7Fm96WEL9/eXK6PWhpNb8FrwSaboxB1I3sdjlLWSaX+Ur3d3OX1hCSd+JOVngyUjdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
